---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: ssh
      ansible_ssh_user: ansible
      ansible_host: 158.160.73.111
      ansible_private_key_file: "~/.ssh/id_ed25519"
#      ansible_python_interpreter: /usr/local/bin/python3.9

vector:
  hosts:
    vector-01:
      ansible_connection: ssh
      ansible_ssh_user: ansible
      ansible_host: 158.160.81.133
      ansible_private_key_file: "~/.ssh/id_ed25519"
#      ansible_python_interpreter: /usr/local/bin/python3.9