---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_database_name: hw_demo_logs
clickhouse_create_table: | 
  CREATE TABLE
  hw_demo_logs_table (
      appname String, 
      facility String, 
      hostname String,
      message String, 
      msgid String, 
      procid UInt16,
      severity String, 
      timestamp DateTime64, 
      version UInt8
      )
  ENGINE = Log;
