---
all:
  hosts:
    nexus-01:
      ansible_host: 158.160.66.59
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: nexus
    ansible_ssh_private_key_file: ~/.ssh/ycloud-vms_rsa