- name: NGINX | Install epel-release
  become: true
  ansible.builtin.package:      # Универсальный модуль, работает и с dnf, и с yum, и с apt
    name: epel-release
    state: present

- name: NGINX | Install NGINX
  become: true
  ansible.builtin.package:
    name: nginx
    state: present

- name: NGINX | Create config
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
