{
 "title": "System Load Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\",job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA 1"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA 5"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA 15"
    }
   ]
  },
  {
   "title": "File Systems Free",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}